[package]
name = "yew_one"
version = "0.1.0"
authors = ["John"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yew = "0.8.0"
stdweb = "0.4.18"
yew-macro = "0.8.0"
